version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.16.0
  docker-build:
    docker:
    - image: docker:stable

jobs:
  lint:
    executor:
      name: default
    steps:
    - checkout
    - run: make lint

  test:
    executor:
      name: default
    steps:
    - checkout
    - run: make test

  build-image:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: mkdir -vp ~/.docker/cli-plugins/
    - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64
    - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
    - run: docker login -u odidev -p 0af07c59-cc6d-407b-bba0-ac8f226b5c5e
    - run: docker run -it --rm --privileged tonistiigi/binfmt --install all
    - run: docker buildx build --platform linux/amd64,linux/arm64 -t odidev/falcosidekick --push .

  build-push-main:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image
    - run:
        command: |
  build-push-ecr:
    executor:
      name: docker-build
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: |
          apk update
          apk add --update make bash
          make build-image
    - run:
        command: |
          docker tag falcosecurity/falcosidekick:latest \
            public.ecr.aws/falcosecurity/falcosidekick:latest
    - run:
        command: |
          apk update
          apk add --update groff less py-pip
          pip install awscli
          aws ecr-public get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin public.ecr.aws/falcosecurity
          docker push public.ecr.aws/falcosecurity/falcosidekick:latest
  release:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pre-requisites
          command: |
            DIR=$(mktemp -d) && pushd $DIR
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install -i $HOME/.local/aws-cli -b $HOME/.local/bin
            popd && rm -r $DIR
      - run:
          name: Prepare env
          command: |
      - run: echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
            aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin public.ecr.aws/falcosecurity
      - run:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /(v)?[0-9]+(\.[0-9]+)*(-.*)*/
      - lint:
          filters:
            tags:
              only: /(v)?[0-9]+(\.[0-9]+)*(-.*)*/
      - build-image:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: master
            tags:
              only: /(v)?[0-9]+(\.[0-9]+)*(-.*)*/
      - build-push-main:
          context: falco
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - build-push-ecr:
          context: test-infra
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - release:
          context:
            - falco
            - test-infra
          requires:
            - test
            - lint
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(v)?[0-9]+(\.[0-9]+)*(-.*)*/
